[package]
name = "seisreinas2"
version = "0.1.0"
authors = ["Fabian Montero <fabian@cluster451.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
